blueprint:
  name: GroupAlarm alarm automation
  description: Trigger some actions when a new GroupAlarm alarm is triggered.
  domain: automation
  author: t.schoenijahn
  source_url: https://github.com/fwmarcel/home-assistant-groupalarm/blob/main/groupalarm-blueprint.yaml
  homeassistant: 
    min_version: 2022.4.0
  input:
    groupalarm_sensor:
      name: GroupAlarm sensor
      description: The sensor which show the current alarm state
      selector:
        entity:
          integration: groupalarm
          domain: sensor
          multiple: false
    self_addressed:
      name: 'Self addressed'
      description: 'Check if I was addressed myself'
      selector:
        boolean: {}
      default: true
    abort_keyword:
      name: (optional) Abort keyword
      description: '(optional) Alarm title/keyword when the action should not be triggered.
        For example: Probealarm'
      selector:
        text:
          multiline: false
    target_action:
      name: Action
      description: What should be done, when a new groupalarm alarm is trigged?
      selector:
        action: {}
mode: parallel
max: 10

variables:
  self_addressed: !input self_addressed
trigger:
  - platform: state
    entity_id: !input groupalarm_sensor
    not_to:
    - unknown
    - !input 'abort_keyword'
condition:
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ is_state(self_addressed, 'off') }}"
      - condition: state
        entity_id: !input groupalarm_sensor
        attribute: self_addressed
        state: true
action:
  - choose:
    default: !input target_action
